class StagesConstants:
    MainMenu = 'main_menu'
    ExitGame = 'exit_game'
    SoloGameMenu = 'solo_game_menu'
    JoinGameMenu = 'join_menu'
    MapEditor = 'map_editor'
    Host_Stage = 'host_stage'
    LoadGame = 'load_game'
    Game = 'game'
    CloseGame = 'close_game'
