class ValidationKeys:
    Player = 'player'
    Players = 'players'
    Skill = 'skill'
    SkillUId = 'skill_uid'
    Global = 'global'
    GameObj = 'game_obj'
    XYCoordinate = 'xy_coord'
    TargetXYCoordinate = 'target_xy_coord'
    Mech = 'mech'
    AllMeches = 'all_meches'
    SkillPool= 'skill_pool'
    DetailsPool= 'details_pool'
    World = 'world'