class Attrs:
    Shape = 'shape_class'
    UID = 'uid'
    XK = 'x_k'
    YK = 'y_k'

    HSizeK = 'h_size_k'
    VSizeK = 'v_size_k'
    AutoDraw = 'auto_draw'
    Parent = 'parent'
    ParentSurface = 'parent_surface'
    Visible = 'visible'
    Active = 'active'

    Color = 'color'
    TextBackColor = 'text_background_color'
    FromLeft = 'from_left'
    FromBot = 'from_bot'
    FromTop = 'from_top'
    PlaceInside = 'place_inside'
    AA = 'antialiasing'
    RawText = 'raw_text'
    Text = 'text'
    TextKwargs = 'text_kwargs'
    InacTextKwargs = 'inactive_text_kwargs'
    Layer = 'layer'

    FontName = 'font_name'
    FontSize = 'font_size'

    SurfaceTransparent = 'surface_transparent'
    SurfaceColor = 'surface_color'
    SurfaceFlags = 'surface_flags'

    PostponeRender = 'postpone_render'
    BorderSize = 'border_size'
    BorderColor = 'border_color'
    InacBorderColor = 'border_color'
    BorderRadius = 'border_radius'
    BorderTopLeftRadius = 'border_top_left_radius'
    BorderTopRightRadius = 'border_top_right_radius'
    BorderBottomLeftRadius = 'border_bottom_left_radius'
    BorderBottomRightRadius = 'border_bottom_right_radius'

    OnClickAction = 'on_click_action'
    OnClickActionArgs = 'on_click_action_args'
    OnClickActionKwargs = 'on_click_action_kwargs'

