from core.world.base.map_save import MapSave


class ForestMap(MapSave):
    def __init__(self):
        dict_tiles_data = [
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0, 0, 0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                       {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                        "vn": "Forest", "hgt": 0, "img": 0}, 0, 0, 0, 0,
                                       {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                        "vn": "Forest", "hgt": 0, "img": 0},
                                       {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                        "vn": "Forest", "hgt": 0, "img": 0},
                                       {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                        "vn": "Forest", "hgt": 0, "img": 0}, 0, 0, 0, 0,
                                       {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                        "vn": "Forest", "hgt": 0, "img": 0}, 0,
                                       {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                        "vn": "Forest", "hgt": 0, "img": 0}, 0, 0,
                                       {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                        "vn": "Forest", "hgt": 0, "img": 0}, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0}, 0, 0, 0, 0,
                                                      0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0}, 0, 0, 0,
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0}, 0, 0, 0, 0,
                                                      0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0,
                                                                                      {"n": "spawn", "hp": 0.0,
                                                                                       "mek": 0.0, "etrn": True,
                                                                                       "dest_t": None, "vn": "Empty",
                                                                                       "hgt": 0, "img": 0}, 0, 0, 0, 0,
                                                                                      0, 0, 0, 0, 0, 0, 0,
                                                                                      {"n": "forest", "hp": 10,
                                                                                       "mek": 0.0, "etrn": False,
                                                                                       "dest_t": None, "vn": "Forest",
                                                                                       "hgt": 0, "img": 0},
                                                                                      {"n": "forest", "hp": 10,
                                                                                       "mek": 0.0, "etrn": False,
                                                                                       "dest_t": None, "vn": "Forest",
                                                                                       "hgt": 0, "img": 0}, 0, 0,
                                                                                      {"n": "forest", "hp": 10,
                                                                                       "mek": 0.0, "etrn": False,
                                                                                       "dest_t": None, "vn": "Forest",
                                                                                       "hgt": 0, "img": 0}, 0,
                                                                                      {"n": "forest", "hp": 10,
                                                                                       "mek": 0.0, "etrn": False,
                                                                                       "dest_t": None, "vn": "Forest",
                                                                                       "hgt": 0, "img": 0}, 0, 0, 0,
                                                                                      {"n": "forest", "hp": 10,
                                                                                       "mek": 0.0, "etrn": False,
                                                                                       "dest_t": None, "vn": "Forest",
                                                                                       "hgt": 0, "img": 0},
                                                                                      {"n": "forest", "hp": 10,
                                                                                       "mek": 0.0, "etrn": False,
                                                                                       "dest_t": None, "vn": "Forest",
                                                                                       "hgt": 0, "img": 0}, 0, 0,
                                                                                      {"n": "forest", "hp": 10,
                                                                                       "mek": 0.0, "etrn": False,
                                                                                       "dest_t": None, "vn": "Forest",
                                                                                       "hgt": 0, "img": 0}, 0, 0,
                                                                                      {"n": "forest", "hp": 10,
                                                                                       "mek": 0.0, "etrn": False,
                                                                                       "dest_t": None, "vn": "Forest",
                                                                                       "hgt": 0, "img": 0}, 0,
                                                                                      {"n": "forest", "hp": 10,
                                                                                       "mek": 0.0, "etrn": False,
                                                                                       "dest_t": None, "vn": "Forest",
                                                                                       "hgt": 0, "img": 0},
                                                                                      {"n": "forest", "hp": 10,
                                                                                       "mek": 0.0, "etrn": False,
                                                                                       "dest_t": None, "vn": "Forest",
                                                                                       "hgt": 0, "img": 0}, 0,
                                                                                      {"n": "forest", "hp": 10,
                                                                                       "mek": 0.0, "etrn": False,
                                                                                       "dest_t": None, "vn": "Forest",
                                                                                       "hgt": 0, "img": 0}, 0,
                                                                                      {"n": "forest", "hp": 10,
                                                                                       "mek": 0.0, "etrn": False,
                                                                                       "dest_t": None, "vn": "Forest",
                                                                                       "hgt": 0, "img": 0},
                                                                                      {"n": "forest", "hp": 10,
                                                                                       "mek": 0.0, "etrn": False,
                                                                                       "dest_t": None, "vn": "Forest",
                                                                                       "hgt": 0, "img": 0},
                                                                                      {"n": "spawn", "hp": 0.0,
                                                                                       "mek": 0.0, "etrn": True,
                                                                                       "dest_t": None, "vn": "Empty",
                                                                                       "hgt": 0, "img": 0}, 0, 0, 0, 0,
                                                                                      0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
             {"n": "spawn", "hp": 0.0, "mek": 0.0, "etrn": True, "dest_t": None, "vn": "Empty", "hgt": 0, "img": 0}, 0,
             0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0,
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0}, 0,
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Spawn", "hgt": 0, "img": 0},
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0}, 0, 0,
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0}, 0, 0,
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0}, 0,
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0}, 0, 0,
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0}, 0,
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                      {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                       "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0}, 0, 0, 0, 0,
                                                      0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Spawn", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0, 0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0,
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0},
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0}, 0,
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0},
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0},
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0},
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0},
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0}, 0, 0,
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0}, 0, 0,
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0}, 0, 0,
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0},
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0},
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0},
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0},
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0},
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0},
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0},
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0},
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0},
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0}, 0, 0, 0, 0, 0, 0,
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0}, 0, 0,
                                                   {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                    "vn": "Forest", "hgt": 0, "img": 0}, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                   0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0}, 0, 0,
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0}, 0,
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0}, 0,
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0}, 0,
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                        {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False,
                                                         "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0}, 0, 0, 0,
                                                        0, 0, 0, 0, 0], [0, 0, 0, 0, 0,
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0}, 0,
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0}, 0,
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0}, 0,
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0}, 0, 0, 0, 0,
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0}, 0,
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0}, 0,
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0},
                                                                         {"n": "forest", "hp": 10, "mek": 0.0,
                                                                          "etrn": False, "dest_t": None, "vn": "Forest",
                                                                          "hgt": 0, "img": 0}, 0, 0, 0, 0, 0, 0, 0, 0,
                                                                         0, 0], [0, 0, 0, 0,
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 0,
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 0, 0, 0,
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 0, 0, 0,
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 0,
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 0, 0,
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 0,
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 0, 0,
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 {"n": "forest", "hp": 10, "mek": 0.0,
                                                                                  "etrn": False, "dest_t": None,
                                                                                  "vn": "Forest", "hgt": 0, "img": 0},
                                                                                 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, {
                "n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              0, 0, {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              0, 0, 0,
                                                                                                              0, 0, 0,
                                                                                                              0, {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              0, 0, {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              0, {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              0, {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              0, {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              {
                                                                                                                  "n": "forest",
                                                                                                                  "hp": 10,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": False,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Forest",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              0, 0, 0,
                                                                                                              0, {
                                                                                                                  "n": "spawn",
                                                                                                                  "hp": 0.0,
                                                                                                                  "mek": 0.0,
                                                                                                                  "etrn": True,
                                                                                                                  "dest_t": None,
                                                                                                                  "vn": "Empty",
                                                                                                                  "hgt": 0,
                                                                                                                  "img": 0},
                                                                                                              0, 0, 0,
                                                                                                              0, 0],
            [0, 0, 0, 0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0, 0, 0, 0, 0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0,
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0}, 0,
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0}, 0, 0, 0, 0, 0,
                                             {"n": "spawn", "hp": 0.0, "mek": 0.0, "etrn": True, "dest_t": None,
                                              "vn": "Empty", "hgt": 0, "img": 0}, 0, 0,
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0}, 0,
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0},
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0}, 0,
                                             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                              "vn": "Forest", "hgt": 0, "img": 0}, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0,
                                                {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                 "vn": "Forest", "hgt": 0, "img": 0}, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                 "vn": "Forest", "hgt": 0, "img": 0}, 0,
                                                {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                 "vn": "Forest", "hgt": 0, "img": 0},
                                                {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                 "vn": "Forest", "hgt": 0, "img": 0},
                                                {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                 "vn": "Forest", "hgt": 0, "img": 0}, 0,
                                                {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                 "vn": "Forest", "hgt": 0, "img": 0},
                                                {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                 "vn": "Forest", "hgt": 0, "img": 0},
                                                {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                 "vn": "Forest", "hgt": 0, "img": 0},
                                                {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                 "vn": "Forest", "hgt": 0, "img": 0},
                                                {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None,
                                                 "vn": "Forest", "hgt": 0, "img": 0}, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0,
             {"n": "forest", "hp": 10, "mek": 0.0, "etrn": False, "dest_t": None, "vn": "Forest", "hgt": 0, "img": 0},
             0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
        super(ForestMap, self).__init__(name='Forest',
                                        path='classic',
                                        dict_tiles_data=dict_tiles_data,
                                        created="2023-04-06 23:36:09.752149",
                                        odd=True,
                                        flat=True,
                                        default=True,
                                        spawns=[(5, 6), (43, 6), (47, 14), (18, 16), (14, 7)],
                                        )


if __name__ == '__main__':
    s = ForestMap()
    new_s = s.copy()
    print(s.__dict__)
    print(new_s.__dict__)
    # assert s == new_s
    print(s.json_tiles_data)
    print(new_s.json_tiles_data)
    print(s.json_tiles_data == new_s.json_tiles_data)
    print(s.json_tiles_data == new_s.json_tiles_data)
    print(s.json_tiles_data is new_s.json_tiles_data)

    print(id(s.json_tiles_data[0]))
    print(id(new_s.json_tiles_data[0]))
    print(s.json_tiles_data[0] == new_s.json_tiles_data[0])
    print(s.json_tiles_data[0] is new_s.json_tiles_data[0])

    print(s.get_tiles_data())
    print(new_s.get_tiles_data())
    assert s.default != new_s.default
