from core.world.base.map_save import MapSave


class ForestMap(MapSave):
    def __init__(self):
        dict_tiles_data = [
            [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
             None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
             None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
            [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
             None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None],
            [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
             None, None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None],
            [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None, None, None,
             None,
             None, None, None, None, None, None, None, None, None, None],
            [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None, None, None,
             None],
            [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None, None, None,
             None,
             None, {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
                    "direction": 0, "height": 0}, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None, None, None,
             None,
             None],
            [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None],
            [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None, None, None,
             None],
            [None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None, None, None,
             None,
             None],
            [None, None, None, None, None, None, None, None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None, None, None],
            [None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None, None],
            [None, None, None, None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None],
            [None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None],
            [None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None],
            [None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None],
            [None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None],
            [None, None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None],
            [None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None, None],
            [None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None, None, None,
             None,
             None, None, None, None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None, None],
            [None, None, None, None, None, None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0},
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None, None, None,
             None,
             None, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None,
             {"name": "forest", "hp": 10, "move_energy_coeff": 0.0, "eternal": False, "destroyed_type": None,
              "direction": 0, "height": 0}, None, None, None, None, None, None, None, None, None, None, None, None,
             None,
             None, None]]
        super(ForestMap, self).__init__(name='Forest',
                                        path='classic',
                                        can_be_saved=False,
                                        can_be_deleted=False,
                                        dict_tiles_data=dict_tiles_data,
                                        )